Add native near transfers Aurora -> Ethereum
Near-One/near-erc20-connector pull request #42
Opened 2024-04-05 15:15 UTC by kiseln

In order to support this we make an XCC call to `migrate_to_ethereum`  method on NEAR. Required wNear is automatically attached to the XCC call, it just needs to be approved to the smart contract.

### Lack of callback

I didn't add an XCC callback, partly because I don't expect `migrate_to_ethereum` to ever fail. It can fail if the amount passed is 0, in which case user will not loose any funds. It can also fail if smart contract address passed is incorrect but that should never happen from our side.

### Creating an account for XCC calls

The implicit account for XCC calls will automatically be created during the first transfer. The caller needs to have additional 2 wNear to pay for that. I think the easiest solution is to make this part of deploy process and execute the first transfer ourselves.

### Upgradeability

Is this something we want to add?

### TODO

Add config for mainnet
Tests?

2024-04-08 17:15 UTC, karim-en requested changes

2024-04-08 17:15 UTC, karim-en commented on aurora/contracts/NearBridge.sol
> +    uint64 constant MIGRATE_TO_ETHEREUM_GAS = 150_000_000_000_000;
Please decrease it to 10TGAS

2024-04-08 17:15 UTC, karim-en commented on aurora/contracts/NearBridge.sol
> +contract NearBridge {
Please make the contract upgradable

2024-04-09 13:47 UTC, kiseln commented on aurora/contracts/NearBridge.sol
> +    uint64 constant MIGRATE_TO_ETHEREUM_GAS = 150_000_000_000_000;
Done in bf6e973a11ec52b5a64a6df295e4df089123bc95

2024-04-09 13:47 UTC, kiseln commented on aurora/contracts/NearBridge.sol
> +contract NearBridge {
Done in bf6e973a11ec52b5a64a6df295e4df089123bc95

2024-04-09 16:31 UTC, karim-en requested changes

2024-04-09 16:31 UTC, karim-en commented on aurora/README.md
> +npm i
Pleas use yarn instead of npm

2024-04-10 14:59 UTC, kiseln commented on aurora/README.md
> +npm i
Done d81def62d5045727d70c47c07990e1eec4c87bcc
I prefer yarn myself actually

2024-04-10 16:03 UTC, karim-en requested changes

2024-04-10 16:03 UTC, karim-en commented on aurora/contracts/NearBridge.sol
> +    function initialize(address wnear, string memory _eNearAccountId) external initializer {
It isn't strictly needed, but it is recommended to add `_disableInitializers` as a best practice.
More details is [here](https://forum.openzeppelin.com/t/what-does-disableinitializers-function-mean/28730) 
```
    // @custom:oz-upgrades-unsafe-allow constructor
    constructor() {
        _disableInitializers();
    }
```

2024-04-10 16:03 UTC, karim-en commented on aurora/README.md
> +## Working with the project
Please also add the verify command to verify the contract on `https://explorer.aurora.dev`

2024-04-10 16:45 UTC, kiseln commented on aurora/contracts/NearBridge.sol
> +            revert AmountIsZero();
Typed errors cost slightly less gas and reduce contract size. They are also part of the ABI so can be easier handled by the front-end. I think it's generally a recommended approach nowadays

2024-04-10 16:48 UTC, kiseln commented on aurora/ignition/aurora_tesnet.params.json
> +    "Bridge": {
Yes it seemed a little weird for me as well but that's the default approach from the docs

2024-04-12 08:08 UTC, olga24912 requested changes

2024-04-12 13:27 UTC, kiseln commented on aurora/hardhat.config.js
> +    testnet_aurora: {
Done 4558f456b0257691151d760ceb81dec76db703d0

2024-04-12 13:27 UTC, kiseln commented on aurora/ignition/aurora_tesnet.params.json
> +{
Done 4558f456b0257691151d760ceb81dec76db703d0

2024-04-12 13:27 UTC, kiseln commented on aurora/README.md
> +npx hardhat compile
Done 4558f456b0257691151d760ceb81dec76db703d0

2024-04-12 13:27 UTC, kiseln commented on aurora/README.md
> +npx hardhat ignition deploy ignition/modules/Bridge.js --network {} --parameters {insert_params_file}
Done 4558f456b0257691151d760ceb81dec76db703d0

2024-04-12 13:27 UTC, kiseln commented on aurora/README.md
> +## Working with the project
Added 4558f456b0257691151d760ceb81dec76db703d0

2024-04-12 13:35 UTC, kiseln commented on aurora/contracts/NearBridge.sol
> +
This is what I originally had but I've noticed then it transfers the tokens twice. Check this https://explorer.testnet.aurora.dev/tx/0xeafabbde871a2b6a5249ddf99b6fb7dddf7653831c990edb4e0bd2954951ac20

It is indeed different from what you would expect looking at examples. Shall we explore this further?

2024-04-12 13:35 UTC, kiseln commented on aurora/contracts/NearBridge.sol
> +
cc @karim-en

2024-04-12 13:54 UTC, olga24912 approved these changes

2024-04-17 14:29 UTC, karim-en requested changes

2024-04-17 14:29 UTC, karim-en commented on aurora/scripts/aurora_mainnet.params.json
> +    "Bridge": {
@kiseln Why the format of mainnet and testnet configs are different?

2024-04-17 14:43 UTC, kiseln commented on aurora/scripts/aurora_mainnet.params.json
> +    "Bridge": {
My bad 1a179a6429df0e4afcdcfba85cc1f6acb8559d5f

2024-04-26 02:39 UTC, paouvrard commented on aurora/contracts/NearBridge.sol
> +
Could you please explain how this is working ? AFAIU the flow should be something similar to fast bridge:
- Pull the wNEAR token from the user wallet:
`wNEAR.transferFrom(msg.sender, address(this), amount);`
- Burn the wNEAR:
`wNEAR.withdrawToNear(bytes(getImplicitNearAccountIdForSelf(), ":unwrap"), amount);`
- Migrate the unwrapped NEAR to Ethereum:
`callMigrateToEthereum.transact();`

2024-04-26 02:52 UTC, karim-en commented on aurora/contracts/NearBridge.sol
> +
@paouvrard the XCC under the hood implements the first 2 action for payable calls, so the tokens are transferd to the implicit account id and then unwrapped.
The 3d action is explicitly called in the contract as you can see.

2024-04-28 23:51 UTC, karim-en approved these changes

2024-04-29 00:57 UTC, karim-en commented on aurora/hardhat.config.js
> +  etherscan: {
The verification configuration  is missing for the Aurora network

2024-04-29 00:59 UTC, karim-en commented on aurora/hardhat.config.js
> +  etherscan: {
80bc8b7d2bd7570bfe2263a9c4cfb5c8cc115abb

2024-04-29 01:04 UTC, merged